name: CI

on: [push]

jobs:
  tests:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install deps
        run: pip3 install -r ${{ secrets.PYPI_PACKAGE_NAME }}/requirements.txt

      - name: Run tests
        run: |
          cd ${{ secrets.PYPI_PACKAGE_NAME }}
          python3 -m unittest
